[package]
name = "supersat"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"

[dependencies]
bitvec = "0.9.0"
itertools = { git = "https://github.com/tobz1000/rust-itertools", branch = "permutations" }
